-- 临时禁用 RLS 用于测试（开发环境）
-- 注意：生产环境不要使用这个脚本！

ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE baustellen DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE items DISABLE ROW LEVEL SECURITY;
ALTER TABLE requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE request_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE request_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
